// ─── Claim Types ─────────────────────────────────────────────────────────────

export type ClaimType =
  | "Cargo"
  | "Commercial"
  | "Damage to hull"
  | "Equipment (disbursement)"
  | "H&M"
  | "H&M fixed and floating objects"
  | "H&M Particular average"
  | "HSE"
  | "Increased value"
  | "Other claim type"
  | "P&I cargo"
  | "P&I crew"
  | "P&I FD&D"
  | "P&I FFO"
  | "P&I personal injury"
  | "P&I pollution"
  | "Pre-loading survey (disbursement)"
  | "Strike & delay";

export type ClaimStatus = "Open" | "Close";

export type Priority = "None" | "Low" | "Medium" | "High" | "Overdue";

export type RecoverableBy = "Insurance" | "Client" | "Other" | "Non-recoverable";

export interface CostAllocation {
  id: string;
  description: string;
  amount: number;
  recoverability: "Insurance" | "Client" | "Non-recoverable" | "none";
  category: string;
}

export interface Claim {
  id: string;
  claimNo: string;
  claimType: ClaimType;
  typeOfCover: string;
  priority: Priority;
  // Vessel & Voyage
  vessel: string;
  fixture: string;
  voyage: string;
  pol: string;
  pod: string;
  location: string;
  portCall: string;
  latitude: string;
  longitude: string;
  // Incident Link
  incidentLinked: boolean;
  incidentNo: string;
  // Parties
  claimant: string;
  claimantReference: string;
  picLegal: string;
  broker: string;
  brokerReference: string;
  brokerContact: string;
  leadingInsurer: string;
  insurerContact: string;
  // Dates
  dateOfIncident: string;
  dateOfNotification: string;
  // Financials
  claimEstimate: number;
  claimAmount: number;
  currency: string;
  deductible: number;
  recoverableBy: RecoverableBy;
  costAllocations: CostAllocation[];
  // Status & Workflow
  status: ClaimStatus;
  insuranceWorkflowStatus: string;
  reviewedByInsurance: boolean;
  approvedByInsurance: boolean;
  signedOffPending: boolean;
  documentChecklist: string[];
  // Standalone claim fields
  damageAsKnown: string;
  stepsTaken: string;
  requiredAssistanceFromInsurance: string;
  representativeOfClaimantPresent: string;
  portAgent: string;
  // General
  createdBy: string;
  createdDate: string;
  remarks: string;
  description: string;
  statusDescription: string;
  // State flags
  archived: boolean;
  deleted: boolean;
}

// ─── Reference data ───────────────────────────────────────────────────────────

export const CLAIM_TYPES: ClaimType[] = [
  "Cargo",
  "Commercial",
  "Damage to hull",
  "Equipment (disbursement)",
  "H&M",
  "H&M fixed and floating objects",
  "H&M Particular average",
  "HSE",
  "Increased value",
  "Other claim type",
  "P&I cargo",
  "P&I crew",
  "P&I FD&D",
  "P&I FFO",
  "P&I personal injury",
  "P&I pollution",
  "Pre-loading survey (disbursement)",
  "Strike & delay",
];

export const CLAIM_STATUSES: ClaimStatus[] = ["Open", "Close"];

export const PRIORITY_OPTIONS: Priority[] = ["None", "Low", "Medium", "High", "Overdue"];

export const TYPE_OF_COVER_OPTIONS: string[] = [
  "Charterer's liability (CL)",
  "Charterer's loss of profit",
  "Charterer's loss of use",
  "Comp. carrier's liability (CCC)",
  "Comp. general liability (CGL)",
  "Ext. cargo liability cover (ECL)",
  "Ext. contractual cover (ECC)",
  "Extended crew cover",
  "Extra war risk insurance (EWRI)",
  "Freight, demurrage, defense (FD&D)",
  "Hull and machinery (H&M)",
  "Kidnap, ransom protection (K&R)",
  "Loss of hire (LOH)",
  "Northern Sea Route buy back (NSR)",
  "Professional indemnity",
  "Project insurance",
  "Property insurance",
  "Protection & Indemnity (P&I)",
  "Strike and delay",
  "TCL and FD&D",
  "War",
];

export const RECOVERABLE_BY_OPTIONS: RecoverableBy[] = [
  "Insurance",
  "Client",
  "Other",
  "Non-recoverable",
];

export const USERS = [
  "Nikhil Mathew",
  "John Doe",
  "Tester Adminren",
  "Aiswaryaa Adminren",
  "Jacson Tom",
  "Safna Basheer",
];

export const LEGAL_USERS = [
  "Arun Kumar",
  "Priya Nair",
  "Ravi Shankar",
  "Deepa Menon",
  "Anoop Krishnan",
  "Lakshmi Pillai",
  "Suresh Babu",
];

export const BROKERS = [
  "Maritime Insurance Brokers",
  "Global Marine Insurance",
  "Seaborne Insurance Group",
  "International Marine Brokers",
  "Maritime Risk Solutions",
  "Marine Legal & Insurance",
];

export const INSURERS = [
  "Lloyd's of London",
  "AXA Marine",
  "Allianz Marine",
  "Gard P&I",
  "UK P&I Club",
  "Britannia P&I Club",
  "Skuld P&I",
  "Swedish Club",
  "North of England P&I",
  "West of England P&I",
  "Shipowners' Club",
];

export const VESSELS = [
  "MV OCEAN STAR",
  "MV PACIFIC VOYAGER",
  "MV ATLANTIC PRIDE",
  "MV SOUTHERN CROSS",
  "MV EASTERN STAR",
  "MV NORTHERN LIGHT",
  "MV WESTERN SPIRIT",
  "MV HORIZON",
  "MV ARCTIC BREEZE",
  "MV TROPICAL WAVE",
  "MV GLOBAL TRADER",
  "MV LIBERTY BELLE",
];

export const PORT_AGENTS = [
  "Inchcape Shipping Services",
  "GAC Shipping",
  "Wilhelmsen Ships Service",
  "Gulf Agency Company (GAC)",
  "Svitzer",
  "Anglo-Eastern",
  "Columbia Ship Management",
  "V.Ships",
  "Bernhard Schulte Shipmanagement",
  "Wallem Group",
  "Transmar Agency",
  "Pacific Basin Shipping",
  "North Sea Shipping Agents",
  "Meridian Port Services",
  "Oceanbridge Maritime",
];

export const ALL_FIXTURES = [
  { id: "FIX-2024-067", vessel: "MV OCEAN STAR",      voyage: "FAI 2601" },
  { id: "FIX-2024-089", vessel: "MV PACIFIC VOYAGER", voyage: "FAI 2502" },
  { id: "FIX-2024-045", vessel: "MV ATLANTIC PRIDE",  voyage: "FAI 2498" },
  { id: "FIX-2024-112", vessel: "MV SOUTHERN CROSS",  voyage: "FAI 2312" },
  { id: "FIX-2024-056", vessel: "MV WESTERN SPIRIT",  voyage: "FAI 2499" },
  { id: "FIX-2024-134", vessel: "MV NORTHERN LIGHT",  voyage: "FAI 2601" },
  { id: "FIX-2024-118", vessel: "MV TROPICAL WAVE",   voyage: "FAI 2715" },
  { id: "FIX-2023-289", vessel: "MV HORIZON",         voyage: "FAI 1998" },
];

// ─── Seed data ────────────────────────────────────────────────────────────────

export const INITIAL_CLAIMS_DATA: Claim[] = [
  {
    id: "1",
    claimNo: "CLM-2024-001",
    claimType: "Cargo",
    typeOfCover: "Ext. cargo liability cover (ECL)",
    priority: "High",
    vessel: "MV OCEAN STAR",
    fixture: "FIX-2024-067",
    voyage: "VOY-2024-045",
    pol: "Rotterdam",
    pod: "Singapore",
    location: "At Sea",
    portCall: "",
    latitude: "12.3456",
    longitude: "45.6789",
    incidentLinked: true,
    incidentNo: "INC-2024-120",
    claimant: "ABC Shipping Ltd",
    claimantReference: "ABC-CLM-2024-045",
    picLegal: "Priya Nair",
    broker: "Maritime Insurance Brokers",
    brokerReference: "MIB-2024-089",
    brokerContact: "James Wilson",
    leadingInsurer: "Lloyd's of London",
    insurerContact: "Sarah Connor",
    dateOfIncident: "2024-02-15",
    dateOfNotification: "2024-02-18",
    claimEstimate: 500000,
    claimAmount: 450000,
    currency: "USD",
    deductible: 25000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Submitted",
    reviewedByInsurance: true,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Logbooks", "Photos", "Claim Notice"],
    createdBy: "Nikhil Mathew",
    createdDate: "2024-02-19",
    remarks: "Urgent follow-up required with surveyor.",
    description: "Container fell overboard during heavy weather causing cargo damage",
    archived: false,
    deleted: false,
  },
  {
    id: "2",
    claimNo: "CLM-2024-002",
    claimType: "H&M",
    typeOfCover: "Hull and machinery (H&M)",
    priority: "High",
    vessel: "MV PACIFIC VOYAGER",
    fixture: "FIX-2024-089",
    voyage: "VOY-2024-062",
    pol: "Houston",
    pod: "Santos",
    location: "Port",
    portCall: "Houston",
    latitude: "",
    longitude: "",
    incidentLinked: true,
    incidentNo: "INC-2024-145",
    claimant: "Pacific Marine Services",
    claimantReference: "PMS-2024-089",
    picLegal: "",
    broker: "Global Marine Insurance",
    brokerReference: "GMI-2024-102",
    brokerContact: "Linda Kovacs",
    leadingInsurer: "AXA Marine",
    insurerContact: "Mark Spencer",
    dateOfIncident: "2024-03-01",
    dateOfNotification: "2024-03-02",
    claimEstimate: 1300000,
    claimAmount: 1250000,
    currency: "USD",
    deductible: 50000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Under Investigation",
    reviewedByInsurance: true,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Photos", "Survey Invitation"],
    createdBy: "Jacson Tom",
    createdDate: "2024-03-03",
    remarks: "",
    description: "Minor collision with pier during docking operations",
    archived: false,
    deleted: false,
  },
  {
    id: "3",
    claimNo: "CLM-2024-003",
    claimType: "Commercial",
    typeOfCover: "Freight, demurrage, defense (FD&D)",
    priority: "Medium",
    vessel: "MV ATLANTIC PRIDE",
    fixture: "FIX-2024-045",
    voyage: "VOY-2024-031",
    pol: "Hamburg",
    pod: "Felixstowe",
    location: "",
    portCall: "",
    latitude: "",
    longitude: "",
    incidentLinked: false,
    incidentNo: "",
    claimant: "Charter Co International",
    claimantReference: "CCI-2024-033",
    picLegal: "",
    broker: "Maritime Risk Solutions",
    brokerReference: "",
    brokerContact: "Tom Richards",
    leadingInsurer: "Allianz Marine",
    insurerContact: "",
    dateOfIncident: "2024-01-20",
    dateOfNotification: "2024-01-25",
    claimEstimate: 90000,
    claimAmount: 85000,
    currency: "USD",
    deductible: 10000,
    recoverableBy: "Client",
    costAllocations: [],
    status: "Close",
    insuranceWorkflowStatus: "Approved",
    reviewedByInsurance: true,
    approvedByInsurance: true,
    signedOffPending: false,
    documentChecklist: ["Delivery Notes", "Claim Notice"],
    createdBy: "Aiswaryaa Adminren",
    createdDate: "2024-01-26",
    remarks: "Settled via arbitration.",
    description: "Vessel delayed due to unexpected port congestion",
    archived: false,
    deleted: false,
  },
  {
    id: "4",
    claimNo: "CLM-2024-004",
    claimType: "P&I personal injury",
    typeOfCover: "Protection & Indemnity (P&I)",
    priority: "Medium",
    vessel: "MV SOUTHERN CROSS",
    fixture: "FIX-2024-112",
    voyage: "VOY-2024-078",
    pol: "Piraeus",
    pod: "Alexandria",
    location: "At Sea",
    portCall: "",
    latitude: "34.5678",
    longitude: "28.9012",
    incidentLinked: true,
    incidentNo: "INC-2024-089",
    claimant: "Crew Member — John Smith",
    claimantReference: "CREW-2024-012",
    picLegal: "",
    broker: "Seaborne Insurance Group",
    brokerReference: "SIG-2024-089",
    brokerContact: "Rachel Kim",
    leadingInsurer: "Britannia P&I Club",
    insurerContact: "David Hawkins",
    dateOfIncident: "2024-02-28",
    dateOfNotification: "2024-03-01",
    claimEstimate: 135000,
    claimAmount: 125000,
    currency: "USD",
    deductible: 5000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Submitted",
    reviewedByInsurance: false,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Logbooks", "Notification Letters"],
    createdBy: "Safna Basheer",
    createdDate: "2024-03-02",
    remarks: "",
    description: "Crew member injured during deck operations",
    archived: false,
    deleted: false,
  },
  {
    id: "5",
    claimNo: "CLM-2024-005",
    claimType: "P&I FD&D",
    typeOfCover: "Freight, demurrage, defense (FD&D)",
    priority: "Low",
    vessel: "MV EASTERN STAR",
    fixture: "FIX-2024-078",
    voyage: "VOY-2024-055",
    pol: "Antwerp",
    pod: "Busan",
    location: "",
    portCall: "",
    latitude: "",
    longitude: "",
    incidentLinked: false,
    incidentNo: "",
    claimant: "Eastern Trade Corporation",
    claimantReference: "ETC-2024-055",
    picLegal: "",
    broker: "Marine Legal & Insurance",
    brokerReference: "MLI-2024-078",
    brokerContact: "Chris Fenton",
    leadingInsurer: "Skuld P&I",
    insurerContact: "Anna Bergström",
    dateOfIncident: "2024-01-10",
    dateOfNotification: "2024-01-15",
    claimEstimate: 340000,
    claimAmount: 325000,
    currency: "USD",
    deductible: 15000,
    recoverableBy: "Other",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Pending Submission",
    reviewedByInsurance: false,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: [],
    createdBy: "John Doe",
    createdDate: "2024-01-16",
    remarks: "Dispute over off-hire period calculation.",
    description: "Dispute over off-hire period calculation",
    archived: false,
    deleted: false,
  },
  {
    id: "6",
    claimNo: "CLM-2024-006",
    claimType: "P&I cargo",
    typeOfCover: "Protection & Indemnity (P&I)",
    priority: "Medium",
    vessel: "MV NORTHERN LIGHT",
    fixture: "FIX-2024-134",
    voyage: "VOY-2024-091",
    pol: "Le Havre",
    pod: "Tilbury",
    location: "Port",
    portCall: "Le Havre",
    latitude: "",
    longitude: "",
    incidentLinked: true,
    incidentNo: "INC-2024-201",
    claimant: "Port Authority",
    claimantReference: "PA-2024-134",
    picLegal: "",
    broker: "International Marine Brokers",
    brokerReference: "IMB-2024-134",
    brokerContact: "Paul Haynes",
    leadingInsurer: "Gard P&I",
    insurerContact: "Ingrid Solberg",
    dateOfIncident: "2024-03-10",
    dateOfNotification: "2024-03-12",
    claimEstimate: 100000,
    claimAmount: 95000,
    currency: "USD",
    deductible: 10000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Submitted",
    reviewedByInsurance: true,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Photos", "Survey Invitation", "Claim Notice"],
    createdBy: "Nikhil Mathew",
    createdDate: "2024-03-13",
    remarks: "",
    description: "Damage to terminal crane during loading operations",
    archived: false,
    deleted: false,
  },
  {
    id: "7",
    claimNo: "CLM-2024-007",
    claimType: "P&I pollution",
    typeOfCover: "Ext. contractual cover (ECC)",
    priority: "Overdue",
    vessel: "MV WESTERN SPIRIT",
    fixture: "FIX-2024-056",
    voyage: "VOY-2024-039",
    pol: "Houston",
    pod: "Veracruz",
    location: "Port",
    portCall: "Houston",
    latitude: "",
    longitude: "",
    incidentLinked: true,
    incidentNo: "INC-2024-167",
    claimant: "Global Commodities Inc",
    claimantReference: "GCI-2024-056",
    picLegal: "",
    broker: "Maritime Insurance Brokers",
    brokerReference: "MIB-2024-167",
    brokerContact: "James Wilson",
    leadingInsurer: "North of England P&I",
    insurerContact: "Elena Moore",
    dateOfIncident: "2024-02-05",
    dateOfNotification: "2024-02-07",
    claimEstimate: 600000,
    claimAmount: 560000,
    currency: "USD",
    deductible: 30000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Under Investigation",
    reviewedByInsurance: false,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Logbooks", "Photos", "Claim Notice", "Notification Letters"],
    createdBy: "Tester Adminren",
    createdDate: "2024-02-08",
    remarks: "Regulatory authority notified. Environmental assessment pending.",
    description: "Cargo contaminated during transfer operations — oil spill",
    archived: false,
    deleted: false,
  },
  {
    id: "8",
    claimNo: "CLM-2023-145",
    claimType: "H&M",
    typeOfCover: "Hull and machinery (H&M)",
    priority: "None",
    vessel: "MV HORIZON",
    fixture: "FIX-2023-289",
    voyage: "VOY-2023-210",
    pol: "Yokohama",
    pod: "Long Beach",
    location: "At Sea",
    portCall: "",
    latitude: "28.9012",
    longitude: "165.3456",
    incidentLinked: true,
    incidentNo: "INC-2023-445",
    claimant: "Horizon Shipping Ltd",
    claimantReference: "HSL-2023-289",
    picLegal: "",
    broker: "Global Marine Insurance",
    brokerReference: "GMI-2023-445",
    brokerContact: "Linda Kovacs",
    leadingInsurer: "Lloyd's of London",
    insurerContact: "Andrew Barnes",
    dateOfIncident: "2023-11-15",
    dateOfNotification: "2023-11-16",
    claimEstimate: 2200000,
    claimAmount: 2100000,
    currency: "USD",
    deductible: 100000,
    recoverableBy: "Insurance",
    costAllocations: [
      { id: "ca-1", description: "Engine room repairs", amount: 1800000, recoverability: "Insurance", category: "Repairs" },
      { id: "ca-2", description: "Surveyor fees", amount: 150000, recoverability: "Insurance", category: "Surveyor" },
      { id: "ca-3", description: "Legal costs", amount: 150000, recoverability: "Insurance", category: "Legal" },
    ],
    status: "Close",
    insuranceWorkflowStatus: "Approved",
    reviewedByInsurance: true,
    approvedByInsurance: true,
    signedOffPending: false,
    documentChecklist: ["Logbooks", "Photos", "Claim Notice", "Survey Invitation", "Delivery Notes"],
    createdBy: "Aiswaryaa Adminren",
    createdDate: "2023-11-17",
    remarks: "Major engine room fire requiring extensive repairs. Settlement agreed.",
    description: "Major engine room fire requiring extensive repairs",
    archived: true,
    deleted: false,
  },
  {
    id: "9",
    claimNo: "CLM-2024-008",
    claimType: "Commercial",
    typeOfCover: "Freight, demurrage, defense (FD&D)",
    priority: "Low",
    vessel: "MV ARCTIC BREEZE",
    fixture: "FIX-2024-101",
    voyage: "VOY-2024-071",
    pol: "Murmansk",
    pod: "Rotterdam",
    location: "",
    portCall: "",
    latitude: "",
    longitude: "",
    incidentLinked: false,
    incidentNo: "",
    claimant: "Nordic Shipping AS",
    claimantReference: "NSA-2024-101",
    picLegal: "",
    broker: "Seaborne Insurance Group",
    brokerReference: "SIG-2024-101",
    brokerContact: "Rachel Kim",
    leadingInsurer: "Swedish Club",
    insurerContact: "Björn Larsson",
    dateOfIncident: "2024-01-28",
    dateOfNotification: "2024-02-01",
    claimEstimate: 185000,
    claimAmount: 175000,
    currency: "USD",
    deductible: 0,
    recoverableBy: "Non-recoverable",
    costAllocations: [],
    status: "Close",
    insuranceWorkflowStatus: "Approved",
    reviewedByInsurance: true,
    approvedByInsurance: true,
    signedOffPending: false,
    documentChecklist: ["Claim Notice", "Delivery Notes"],
    createdBy: "Safna Basheer",
    createdDate: "2024-02-02",
    remarks: "Main engine failure causing voyage delay. Settled.",
    description: "Main engine failure causing voyage delay",
    archived: false,
    deleted: false,
  },
  {
    id: "10",
    claimNo: "CLM-2024-009",
    claimType: "P&I personal injury",
    typeOfCover: "Protection & Indemnity (P&I)",
    priority: "None",
    vessel: "MV TROPICAL WAVE",
    fixture: "FIX-2024-118",
    voyage: "VOY-2024-082",
    pol: "Santos",
    pod: "Mombasa",
    location: "At Sea",
    portCall: "",
    latitude: "-15.4567",
    longitude: "32.1234",
    incidentLinked: true,
    incidentNo: "INC-2024-178",
    claimant: "Crew Member — Miguel Santos",
    claimantReference: "CREW-2024-019",
    picLegal: "",
    broker: "Maritime Risk Solutions",
    brokerReference: "MRS-2024-178",
    brokerContact: "Tom Richards",
    leadingInsurer: "UK P&I Club",
    insurerContact: "Helen Watts",
    dateOfIncident: "2024-02-20",
    dateOfNotification: "2024-02-21",
    claimEstimate: 50000,
    claimAmount: 45000,
    currency: "USD",
    deductible: 2500,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Close",
    insuranceWorkflowStatus: "Approved",
    reviewedByInsurance: true,
    approvedByInsurance: true,
    signedOffPending: false,
    documentChecklist: ["Logbooks", "Notification Letters"],
    createdBy: "John Doe",
    createdDate: "2024-02-22",
    remarks: "",
    description: "Crew member suffered heat exhaustion in engine room",
    archived: false,
    deleted: false,
  },
  {
    id: "11",
    claimNo: "CLM-2024-010",
    claimType: "P&I FD&D",
    typeOfCover: "Freight, demurrage, defense (FD&D)",
    priority: "Low",
    vessel: "MV GLOBAL TRADER",
    fixture: "FIX-2024-092",
    voyage: "VOY-2024-065",
    pol: "Durban",
    pod: "Colombo",
    location: "",
    portCall: "",
    latitude: "",
    longitude: "",
    incidentLinked: false,
    incidentNo: "",
    claimant: "International Trade Partners",
    claimantReference: "ITP-2024-092",
    picLegal: "",
    broker: "Marine Legal & Insurance",
    brokerReference: "MLI-2024-092",
    brokerContact: "Chris Fenton",
    leadingInsurer: "Shipowners' Club",
    insurerContact: "Fiona Hughes",
    dateOfIncident: "2024-02-12",
    dateOfNotification: "2024-02-16",
    claimEstimate: 225000,
    claimAmount: 215000,
    currency: "USD",
    deductible: 10000,
    recoverableBy: "Client",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Pending Submission",
    reviewedByInsurance: false,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: [],
    createdBy: "Tester Adminren",
    createdDate: "2024-02-17",
    remarks: "Dispute over demurrage calculation at discharge port.",
    description: "Dispute over demurrage calculation at discharge port",
    archived: false,
    deleted: false,
  },
  {
    id: "12",
    claimNo: "CLM-2024-011",
    claimType: "Cargo",
    typeOfCover: "Ext. cargo liability cover (ECL)",
    priority: "Medium",
    vessel: "MV LIBERTY BELLE",
    fixture: "FIX-2024-125",
    voyage: "VOY-2024-088",
    pol: "Felixstowe",
    pod: "Mumbai",
    location: "Port",
    portCall: "Mumbai",
    latitude: "",
    longitude: "",
    incidentLinked: false,
    incidentNo: "",
    claimant: "Continental Logistics",
    claimantReference: "CL-2024-125",
    picLegal: "",
    broker: "International Marine Brokers",
    brokerReference: "IMB-2024-125",
    brokerContact: "Paul Haynes",
    leadingInsurer: "West of England P&I",
    insurerContact: "Nigel Foster",
    dateOfIncident: "2024-03-05",
    dateOfNotification: "2024-03-08",
    claimEstimate: 190000,
    claimAmount: 180000,
    currency: "USD",
    deductible: 10000,
    recoverableBy: "Insurance",
    costAllocations: [],
    status: "Open",
    insuranceWorkflowStatus: "Submitted",
    reviewedByInsurance: false,
    approvedByInsurance: false,
    signedOffPending: false,
    documentChecklist: ["Delivery Notes", "Photos"],
    createdBy: "Nikhil Mathew",
    createdDate: "2024-03-09",
    remarks: "Shortage discovered on cargo discharge.",
    description: "Shortage discovered on cargo discharge",
    archived: false,
    deleted: false,
  },
];
