// Version 2.0 — single flat Type of Cover list (BRD v2, Insurance Category framework removed)
export const TYPE_OF_COVER_V2 = [
  "Charterer's liability (CL)",
  "Charterer's loss of profit",
  "Charterer's loss of use",
  "Comp. carrier's liability (CCC)",
  "Comp. general liability (CGL)",
  "Ext. cargo liability cover (ECL)",
  "Ext. contractual cover (ECC)",
  "Extended crew cover",
  "Extra war risk insurance (EWRI)",
  "Freight, demurrage, defense (FD&D)",
  "Hull and machinery (H&M)",
  "Kidnap, ransom protection (K&R)",
  "Loss of hire (LOH)",
  "Northern Sea Route buy back (NSR)",
  "Professional indemnity",
  "Project insurance",
  "Property insurance",
  "Protection & Indemnity (P&I)",
  "Strike and delay",
  "TCL and FD&D",
  "War",
];
